use setup
mdolab/multipoint pull request #5
Opened 2020-06-12 14:10 UTC by joanibal

## Purpose
Change the structure of the repo to use the `setup.py` method of installation. 
This will make it easier to install environment specific packages and specify dependencies. 

One can install the repo now by doing
`make` (if applicable) and `pip install .`

## Type of change
- Code style update (formatting, renaming)
- Refactoring (no functional changes, no API changes)

## Checklist
- [x] I have run unit and regression tests which pass locally with my changes

2020-06-15 14:45 UTC, marcomangano requested changes
testMP.py has a deprecated `import mdo_import_helper` that should be changed with mpi4py

2020-06-15 20:09 UTC, joanibal commented
So `testMP.py` should be removed?
I'm not sure what you mean by "changed with mpi4py"

2020-06-16 03:51 UTC, marcomangano commented
Sorry, my bad, I mean that `from mdo_import_helper import MPI, mpiPrint` should be changed into `from mpi4py import MPI, mpiPrint`. I don't think we should remove this example file, although we might discuss its update at a later stage.

2020-06-16 20:45 UTC, eirikurj approved these changes

2020-06-16 20:47 UTC, merged